build: off

skip_commits:
  files:
    - README.md
  message: /update readme.*|update docs.*|update media.*|update appveyor.*/

version: 0.1.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

clone_folder: C:\Projects\PoshBotPlugins\

environment:
  NuGetApiKey:
    secure: yT4y8CJjmfXG3XtpPURja5wnvvASrxJrHDDWAjCzLaDY8eMNn8YrsZR5nnU1izGn

install:
  - ps: . .\helper\Update-PowerShellGallery.ps1
  - ps: Install-Module PsScriptAnalyzer -Force
  - ps: Install-Module Pester -Force

test_script:
  - ps: $res = Invoke-Pester -Path ".\tests" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
  - ps: Update-PowerShellGallery -Path "$($env:APPVEYOR_BUILD_FOLDER)\poshbot.veeam\ -ApiKey $env:NuGetApiKey