skip_commits:
  files:
    - README.md
  message: /update readme.*|update docs.*|update media.*|update appveyor.*/

version: 0.1.{build}

pull_requests:
  do_not_increment_build_number: true

#branches:
#  only:
#  - master

clone_folder: C:\Projects\PoshBotPlugins\

environment:
  NuGetApiKey:
    secure: yT4y8CJjmfXG3XtpPURja5wnvvASrxJrHDDWAjCzLaDY8eMNn8YrsZR5nnU1izGn
  ModuleName: poshbot.veeam

install:
  - ps: . .\helper\Update-PowerShellGallery.ps1
  - ps: . .\appveyor\install.ps1

build_script:
  - ps: . .\appveyor\build.ps1

test_script:
  - ps: . .\appveyor\test.ps1

deploy_script:
  - ps: . .\appveyor\deploy.ps1
